<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu')->insert([
            [
                'menu_id' => 'f1e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'produk',
                'menu_title' => 'Produk',
                'menu_order' => '01',
                'menu_parent' => null,
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 1,
                'menu_icon' => 'fas fa-lg fa-list-ul ps-2 pe-2 text-center text-dark',
                'menu_description' => null,
            ],
            [
                'menu_id' => 'b5w82d3p-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'produk-Create',
                'menu_title' => 'Produk Create',
                'menu_order' => '01.01',
                'menu_parent' => 'f1e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'p3h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'produk-Read',
                'menu_title' => 'Produk Read',
                'menu_order' => '01.02',
                'menu_parent' => 'f1e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'q0h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'produk-Update',
                'menu_title' => 'Produk Update',
                'menu_order' => '01.03',
                'menu_parent' => 'f1e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'z1h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'produk-Delete',
                'menu_title' => 'Produk Delete',
                'menu_order' => '01.04',
                'menu_parent' => 'f1e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer',
                'menu_title' => 'Customer',
                'menu_order' => '03',
                'menu_parent' => null,
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 1,
                'menu_icon' => 'fas fa-lg fa-list-ul ps-2 pe-2 text-center text-dark',
                'menu_description' => null,
            ],
            [
                'menu_id' => 'k5w82d3p-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer-Create',
                'menu_title' => 'Customer Create',
                'menu_order' => '03.01',
                'menu_parent' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '13h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer-Read',
                'menu_title' => 'Customer Read',
                'menu_order' => '03.02',
                'menu_parent' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '8ih69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer-Update',
                'menu_title' => 'Customer Update',
                'menu_order' => '03.03',
                'menu_parent' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'm3h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer-Approve',
                'menu_title' => 'Customer Approve',
                'menu_order' => '03.04',
                'menu_parent' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'p0h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'customer-Delete',
                'menu_title' => 'Customer Delete',
                'menu_order' => '03.04',
                'menu_parent' => '41e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => 'a4m12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'member',
                'menu_title' => 'Member',
                'menu_order' => '04',
                'menu_parent' => null,
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 1,
                'menu_icon' => 'fas fa-lg fa-list-ul ps-2 pe-2 text-center text-dark',
                'menu_description' => null,
            ],
            [
                'menu_id' => '81e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'user',
                'menu_title' => 'User',
                'menu_order' => '05',
                'menu_parent' => null,
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 1,
                'menu_icon' => 'fas fa-lg fa-list-ul ps-2 pe-2 text-center text-dark',
                'menu_description' => null,
            ],
            [
                'menu_id' => '25w82d3p-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'user-Create',
                'menu_title' => 'User Create',
                'menu_order' => '05.01',
                'menu_parent' => '81e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '43h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'user-Read',
                'menu_title' => 'User Read',
                'menu_order' => '05.02',
                'menu_parent' => '81e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '10h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'user-Update',
                'menu_title' => 'User Update',
                'menu_order' => '05.03',
                'menu_parent' => '81e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '71h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'user-Delete',
                'menu_title' => 'User Delete',
                'menu_order' => '05.04',
                'menu_parent' => '81e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '01e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'hakakses',
                'menu_title' => 'Hak Akses',
                'menu_order' => '06',
                'menu_parent' => null,
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 1,
                'menu_icon' => 'fas fa-lg fa-list-ul ps-2 pe-2 text-center text-dark',
                'menu_description' => null,
            ],
            [
                'menu_id' => '05w82d3p-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'hakakses-Create',
                'menu_title' => 'Hak Akses Create',
                'menu_order' => '06.01',
                'menu_parent' => '01e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '53h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'hakakses-Read',
                'menu_title' => 'Hak Akses Read',
                'menu_order' => '06.02',
                'menu_parent' => '01e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '60h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'hakakses-Update',
                'menu_title' => 'Hak Akses Update',
                'menu_order' => '06.03',
                'menu_parent' => '01e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
            [
                'menu_id' => '91h69n1j-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_kode' => 'hakakses-Delete',
                'menu_title' => 'Hak Akses Delete',
                'menu_order' => '06.04',
                'menu_parent' => '01e12a1a-67cd-408e-b4a8-e6c6ee1d6aa7',
                'menu_link' => 'javascript:void(0)',
                'menu_isaktif' => 1,
                'menu_level' => 2,
                'menu_icon' => null,
                'menu_description' => null,
            ],
        ]);
    }
}
